pipeline {
  agent any

  tools {
    jdk   'JDK17'
    maven 'Maven3'
  }

  stages {
    stage('Checkout') {
      steps {
        git url: 'https://github.com/RitamBhattacharya/RoomServiceAPIRestAssured', branch: 'main'
      }
    }

    stage('Build & Test') {
      steps {
        withMaven(maven: 'Maven3') {
          bat 'mvn -B clean test -Dsurefire.suiteXmlFiles=testng.xml'
        }
      }
    }
  }

  post {
    always {
      // Publish JUnit results (generated by Surefire)
      junit allowEmptyResults: true, testResults: 'target/surefire-reports/*.xml'

      // Publish TestNG report
      testNG(
        reportFilenamePattern: 'target/surefire-reports/testng-results.xml',
        showFailedBuilds: true,
        escapeTestDescp: true,
        escapeExceptionMsg: true
      )

      // Publish Extent Report HTML
      publishHTML(target: [
        reportDir: 'target/ExtentReports',
        reportFiles: 'RoomServiceApiReport.html',
        reportName: 'Room Service API Report',
        keepAll: true,
        alwaysLinkToLastBuild: true,
        allowMissing: true
      ])

      // Archive reports as artifacts
      archiveArtifacts artifacts: 'target/ExtentReports/**, target/surefire-reports/**',
                       fingerprint: true,
                       allowEmptyArchive: true
    }
  }
}
